<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="JAGA" name="testNG_Concepts.Mutliple_Tests" tests="4" failures="0" timestamp="26 Sep 2018 03:09:44 GMT" time="0.063" errors="1">
  <testcase name="testMath" time="0.016" classname="testNG_Concepts.Mutliple_Tests">
    <error type="org.testng.TestException" message="
Method Mutliple_Tests.testMath()[pri:0, instance:testNG_Concepts.Mutliple_Tests@27f723] should have thrown an exception of type class java.lang.ArithmeticException">
      <![CDATA[org.testng.TestException: 
Method Mutliple_Tests.testMath()[pri:0, instance:testNG_Concepts.Mutliple_Tests@27f723] should have thrown an exception of type class java.lang.ArithmeticException
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:80)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1139)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:612)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testMath -->
  <testcase name="testB" time="0.015" classname="testNG_Concepts.Mutliple_Tests"/>
  <testcase name="testA" time="0.032" classname="testNG_Concepts.Mutliple_Tests"/>
  <testcase name="testC" time="0.000" classname="testNG_Concepts.Mutliple_Tests"/>
</testsuite> <!-- testNG_Concepts.Mutliple_Tests -->
